#pragma once

#include <cstdint>

namespace Trinity
{
    enum class KeyCode : std::uint16_t
    {
        UNKNOWN = 0,

        TR_SPACE = 32,
        TR_APOSTROPHE = 39,
        TR_COMMA = 44, TR_MINUS = 45, TR_PERIOD = 46, TR_SLASH = 47,

        TR_D0 = 48, TR_D1, TR_D2, TR_D3, TR_D4, TR_D5, TR_D6, TR_D7, TR_D8, TR_D9,

        TR_SEMICOLON = 59,
        TR_EQUAL = 61,

        TR_A = 65, TR_B, TR_C, TR_D, TR_E, TR_F, TR_G, TR_H, TR_I, TR_J, TR_K, TR_L, TR_M, TR_N, TR_O, TR_P, TR_Q, TR_R, TR_S, TR_T, TR_U, TR_V, TR_W, TR_X, TR_Y, TR_Z,

        TR_LEFT_BRACKET = 91, TR_BACKSLASH = 92, TR_RIGHT_BRACKET = 93,
        TR_GRAVE_ACCENT = 96,

        TR_ESCAPE = 256, TR_ENTER, TR_TAB, TR_BACKSPACE, TR_INSERT, TR_DELETE,
        TR_RIGHT = 262, TR_LEFT, TR_DOWN, TR_UP,
        TR_PAGE_UP = 266, TR_PAGE_DOWN, TR_HOME, TR_END,
        TR_CAPS_LOCK = 280, TR_SCROLL_LOCK, TR_NUM_LOCK, TR_PRINT_SCREEN, TR_PAUSE,

        TR_F1 = 290, TR_F2, TR_F3, TR_F4, TR_F5, TR_F6, TR_F7, TR_F8, TR_F9, TR_F10, TR_F11, TR_F12,
        TR_F13, TR_F14, TR_F15, TR_F16, TR_F17, TR_F18, TR_F19, TR_F20, TR_F21, TR_F22, TR_F23, TR_F24,

        TR_KP0 = 320, TR_KP1, TR_KP2, TR_KP3, TR_KP4, TR_KP5, TR_KP6, TR_KP7, TR_KP8, TR_KP9,
        TR_KP_DECIMAL = 330, TR_KP_DIVIDE, TR_KP_MULTIPLY, TR_KP_SUBTRACT, TR_KP_ADD, TR_KP_ENTER,

        TR_LEFT_SHIFT = 340, TR_LEFT_CONTROL, TR_LEFT_ALT, TR_LEFT_SUPER,
        TR_RIGHT_SHIFT = 344, TR_RIGHT_CONTROL, TR_RIGHT_ALT, TR_RIGHT_SUPER,
        TR_MENU = 348,

        Count
    };
}