#pragma once

#include "Trinity/Asset/Asset.hpp"
#include "Trinity/Asset/AssetManager.hpp"
#include "Trinity/Asset/AssetRegistry.hpp"
#include "Trinity/Asset/EnvironmentAsset.hpp"
#include "Trinity/Asset/MaterialAsset.hpp"
#include "Trinity/Asset/MaterialData.hpp"
#include "Trinity/Asset/MaterialLoader.hpp"
#include "Trinity/Asset/MeshAsset.hpp"
#include "Trinity/Asset/ModelData.hpp"
#include "Trinity/Asset/TextureAsset.hpp"

#include "Trinity/Core/Application.hpp"
#include "Trinity/Core/Assert.hpp"
#include "Trinity/Core/Base.hpp"
#include "Trinity/Core/ConsoleVariable.hpp"
#include "Trinity/Core/Expected.hpp"
#include "Trinity/Core/FileDialog.hpp"
#include "Trinity/Core/FrameAllocator.hpp"
#include "Trinity/Core/JobSystem.hpp"
#include "Trinity/Core/Layer.hpp"
#include "Trinity/Core/Log.hpp"
#include "Trinity/Core/MainThread.hpp"
#include "Trinity/Core/Memory.hpp"
#include "Trinity/Core/Profiler.hpp"
#include "Trinity/Core/SharedLibrary.hpp"
#include "Trinity/Core/Timestep.hpp"
#include "Trinity/Core/UUID.hpp"
#include "Trinity/Core/Window.hpp"

#include "Trinity/FileSystem/FileSystem.hpp"
#include "Trinity/FileSystem/MemorySource.hpp"

#include "Trinity/Events/ApplicationEvent.hpp"
#include "Trinity/Events/Event.hpp"
#include "Trinity/Events/KeyEvent.hpp"
#include "Trinity/Events/MouseEvent.hpp"

#include "Trinity/Input/Input.hpp"
#include "Trinity/Input/KeyCodes.hpp"
#include "Trinity/Input/MouseCodes.hpp"

#include "Trinity/Physics/CollisionShape.hpp"
#include "Trinity/Physics/PhysicsTypes.hpp"
#include "Trinity/Physics/PhysicsWorld3D.hpp"

#include "Trinity/Renderer/DebugDraw.hpp"
#include "Trinity/Renderer/FrameGraph.hpp"
#include "Trinity/Renderer/GraphicsAPI.hpp"
#include "Trinity/Renderer/PickID.hpp"
#include "Trinity/Renderer/Renderer2D.hpp"
#include "Trinity/Renderer/Renderer3D.hpp"
#include "Trinity/Renderer/ToneMapping.hpp"
#include "Trinity/RHI/Device.hpp"

#include "Trinity/Project/Project.hpp"

#include "Trinity/Scene/ComponentType.hpp"
#include "Trinity/Scene/Components.hpp"
#include "Trinity/Scene/Entity.hpp"
#include "Trinity/Scene/Scene.hpp"
#include "Trinity/Scene/SceneRuntime.hpp"
#include "Trinity/Scene/SceneSerializer.hpp"
#include "Trinity/Scene/SimulationClock.hpp"

#include "Trinity/UI/Icons.hpp"
#include "Trinity/UI/ImGuiLayer.hpp"