if(NOT DEFINED TRINITY_PLATFORM)
    if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
        set(TRINITY_PLATFORM "Windows")
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        set(TRINITY_PLATFORM "Linux")
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
        set(TRINITY_PLATFORM "macOS")
    else()
        message(FATAL_ERROR "Unsupported platform '${CMAKE_SYSTEM_NAME}'. Console builds must set TRINITY_PLATFORM from their toolchain file.")
    endif()
endif()

set(_trinity_known_platforms Windows Linux macOS Xbox PlayStation Switch)
if(NOT TRINITY_PLATFORM IN_LIST _trinity_known_platforms)
    message(FATAL_ERROR "TRINITY_PLATFORM='${TRINITY_PLATFORM}' is not one of: ${_trinity_known_platforms}")
endif()

string(TOUPPER "${TRINITY_PLATFORM}" TRINITY_PLATFORM_UPPER)

set(_d3d12_default OFF)
set(_vulkan_default OFF)
if(TRINITY_PLATFORM STREQUAL "Windows")
    set(_d3d12_default ON)
    set(_vulkan_default ON)
elseif(TRINITY_PLATFORM STREQUAL "Xbox")
    set(_d3d12_default ON)
elseif(TRINITY_PLATFORM STREQUAL "Linux" OR TRINITY_PLATFORM STREQUAL "macOS")
    set(_vulkan_default ON)
endif()

option(TRINITY_RHI_D3D12 "Compile the Direct3D 12 backend" ${_d3d12_default})
option(TRINITY_RHI_VULKAN "Compile the Vulkan 1.4 backend"  ${_vulkan_default})
option(TRINITY_RHI_METAL "Compile the native Metal backend" OFF)

if(TRINITY_RHI_D3D12 AND NOT (TRINITY_PLATFORM STREQUAL "Windows" OR TRINITY_PLATFORM STREQUAL "Xbox"))
    message(FATAL_ERROR "TRINITY_RHI_D3D12 is only available on Windows and Xbox")
endif()
if(TRINITY_RHI_METAL AND NOT TRINITY_PLATFORM STREQUAL "macOS")
    message(FATAL_ERROR "TRINITY_RHI_METAL is only available on macOS")
endif()